#!/bin/bash

# CONFIGURATION
. "../.wallchangerrc"

if [ ! -d "$WPATH" ]; then
	echo "The folder $PATH does not exist"
	exit
fi

# NOMBRE DE FICHIERS DANS LE REPERTOIRE
FILE_COUNT=$(find $WPATH -type f | wc -l)
echo "Number of files : $FILE_COUNT"

# CREATE WALLPAERS HISTORY IF NOT EXIST
HIST_FILE="$HOME/.wallchanger/wallpapers-history"

change_wallpaper()
{
	# IF THE HISTORY FILE HAS BEEN DELETE. WE CREATE IT
	if [ ! -f "$HIST_FILE" ]; then
		touch "$HIST_FILE"
	fi

	I=0
	for H in $(cat "$HIST_FILE"); do
	    HIST_LIST[$I]="$H"
	    I=$(expr $I + 1)
	done


	file=$(find $WPATH -type f | shuf -n 1)
	while [[ " ${HIST_LIST[*]} " == *" $file "* ]]; do
		file=$(find $WPATH -type f | shuf -n 1)
	done

	echo "WALLPAPER TO LOAD : $file"

	gsettings set org.gnome.desktop.background picture-uri "$file"
	gsettings set org.gnome.desktop.background picture-options zoom

	echo "HISTORY COUNT : $(expr $I + 1)"
	echo "TOTAL COUNT   : $FILE_COUNT"

	if [ "$(expr $I + 1)" = "$FILE_COUNT" ]
	then
		echo "ALL WALLPAPER USED > REMOVE HISTORY"
		rm "$HIST_FILE"
	else
		echo "ADD CURRENT WALLPAPER TO HISTORY"
		echo "$file" >> "$HIST_FILE"
	fi

	echo " -- "

}

if [[ "$WSLEEP" < "5" ]]; then
	WSLEEP='5'
fi

while [[ 1 ]]; do
	change_wallpaper
	sleep $WSLEEP
done
