#!/bin/sh -e

PATH="/usr/sbin:/usr/bin:/sbin:/bin"
DESC="Wallchanger Daemon"
NAME="wallchanger"
DAEMON="/home/$HOME/.wallchanger/$NAME"
DAEMON_ARGS="--options args"
PIDFILE="/var/run/$NAME.pid"
SCRIPTNAME="/etc/init.d/$NAME"
USERNAME="_username_"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

d_start () {
	log_daemon_msg "Starting system $DESC"
	start-stop-daemon --background --name $NAME --start --quiet --chuid $DAEMONUSER --exec $DAEMON -- $daemon_OPT
	log_end_msg $?
}

d_stop () {
	log_daemon_msg "Stopping system $DESC"
	start-stop-daemon --name $NAME --stop --retry 5 --quiet --name $NAME
	log_end_msg $?
}

case "$1" in

	start|stop)
		d_${1}
		;;

	restart|reload|force-reload)
			d_stop
			d_start
		;;

	force-stop)
		d_stop
		killall -q $daemon_NAME || true
		sleep 2
		killall -q -9 $daemon_NAME || true
		;;

	status)
		status_of_proc "$daemon_NAME" "$DAEMON" "system-wide $daemon_NAME" && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/$daemon_NAME {start|stop|force-stop|restart|reload|force-reload|status}"
		exit 1
		;;
esac
exit 0
#
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
