#!/bin/sh

### BEGIN INIT INFO
# Provides:          wallchanger
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Change automatically your wallpaper
# Description:       Wallchanger
### END INIT INFO

PATH="/usr/sbin:/usr/bin:/sbin:/bin"
DESC="Wallchanger Daemon"
NAME="wallchanger"
DAEMON="_userhome_/.wallchanger/$NAME"
PIDFILE="/var/run/$NAME.pid"
SCRIPTNAME="/etc/init.d/$NAME"
DAEMONUSER="_username_"

[ -x "$DAEMON" ] || exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

d_start () {
	start-stop-daemon --start --quiet --chuid $DAEMONUSER \
	--make-pidfile --pidfile $PIDFILE --background \
	--exec /bin/bash -- -c "$DAEMON > /var/log/wallchanger.log 2>&1"

	# start-stop-daemon --background --name $NAME \
	# --start --chuid $DAEMONUSER \
	# --exec $DAEMON >> /var/log/wallchanger.log
}

d_stop () {
	start-stop-daemon --stop --quiet --chuid $DAEMONUSER \
	--pidfile $PIDFILE \
	--retry 5
	--exec /bin/bash -- -c "$DAEMON > /var/log/wallchanger.log 2>&1"
}

case "$1" in

	start|stop)
		d_${1}
		;;

	restart|reload|force-reload)
			d_stop
			d_start
		;;

	force-stop)
		d_stop
		killall -q $NAME || true
		sleep 2
		killall -q -9 $NAME || true
		;;

	status)
		status_of_proc "$NAME" "$DAEMON" "system-wide $NAME" && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/$NAME {start|stop|force-stop|restart|reload|force-reload|status}"
		exit 1
		;;
esac
exit 0
